export const cartData = [
  {
    date: '',
    hour: 'Morning',
    list: [
      {
        imageUrl: require('../assets/b1.png'),
        itemName: 'Pancakes and maple syrup',
        price: 1830,
        time: '8:45 AM',
        delivery: 'DOORSTEP DELIVERY',
        count: 0,
      },
      {
        imageUrl: require('../assets/b2.png'),
        itemName: 'Scrambled Eggs and Milk',
        price: 2400,
        time: '8:45 AM',
        delivery: 'DOORSTEP DELIVERY',
        count: 0,
      },
      {
        imageUrl: require('../assets/b3.png'),
        itemName: 'Spicy Nigerian Jollof Rice',
        price: 650,
        time: '8:45 AM',
        delivery: 'DOORSTEP DELIVERY',
        count: 0,
      },
    ],
  },
  {
    date: '',
    hour: 'Afternoon',
    list: [
      {
        imageUrl: require('../assets/b4.png'),
        itemName: 'Goat Meat Pepper Soup',
        price: 1750,
        time: '8:45 AM',
        delivery: 'DOORSTEP DELIVERY',
        count: 0,
      },
      {
        imageUrl: require('../assets/b1.png'),
        itemName: 'Strawberry and Yoghurt parfait',
        price: 2200,
        time: '8:45 AM',
        delivery: 'DOORSTEP DELIVERY',
        count: 0,
      },
      {
        imageUrl: require('../assets/b2.png'),
        itemName: 'Pancakes and Strawberry',
        price: 999,
        time: '8:45 AM',
        delivery: 'DOORSTEP DELIVERY',
        count: 0,
      },
    ],
  },
  {
    date: '',
    hour: 'Night',
    list: [
      {
        imageUrl: require('../assets/b3.png'),
        itemName: 'Scrambled Eggs and Milk',
        price: 1965,
        time: '8:45 AM',
        delivery: 'DOORSTEP DELIVERY',
        count: 0,
      },
      {
        imageUrl: require('../assets/b1.png'),
        itemName: 'Goat Mea)t Pepper Soup',
        price: 1300,
        time: '8:45 AM',
        delivery: 'DOORSTEP DELIVERY',
        count: 0,
      },
      {
        imageUrl: require('../assets/b4.png'),
        itemName: 'Pancakes and Strawberry',
        price: 2488,
        time: '8:45 AM',
        delivery: 'DOORSTEP DELIVERY',
        count: 0,
      },
    ],
  },
  {
    date: '',
    hour: 'Morning',
    list: [
      {
        imageUrl: require('../assets/b1.png'),
        itemName: 'Scrambled Eggs and Milk',
        price: 1800,
        time: '8:45 AM',
        delivery: 'DOORSTEP DELIVERY',
        count: 0,
      },
      {
        imageUrl: require('../assets/b2.png'),
        itemName: 'Pancakes and Strawberry',
        price: 1200,
        time: '8:45 AM',
        delivery: 'DOORSTEP DELIVERY',
        count: 0,
      },
      {
        imageUrl: require('../assets/b3.png'),
        itemName: 'Goat Meat Pepper Soup',
        price: 645,
        time: '8:45 AM',
        delivery: 'DOORSTEP DELIVERY',
        count: 0,
      },
    ],
  },
];
