export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const FIAT_CURRENCY ="FIAT_CURRENCY";
export const CRYPTO_CURRENCY ="CRYPTO_CURRENCY";
export const SELECTED_FIAT_CURRENCY ="SELECTED_FIAT_CURRENCY";
export const SELECTED_CRYPTO_CURRENCY="SELECTED_CRYPTO_CURRENCY";
export const CURRENCY_RATE="CURRENCY_RATE";



