import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  main: {
    flexDirection: 'column',
    position: 'relative',
    flex: 1,
  },
  headerText: {
    color: 'white',
    position: 'absolute',
    bottom: 75,
    zIndex: 22,
    padding: 24,
    lineHeight: 24,
    fontSize: 16,
    letterSpacing: 1,
  },
  header: {
    height: 300,
  },
  dark: {
    height: '100%',
    width: '100%',
    position: 'absolute',
    zIndex: 20,
    backgroundColor: '#00000075',
  },
  itemImg: {width: 128, height: 112, borderRadius: 10, alignSelf: 'center'},
  itemWrapper: {
    width: 148,
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    backgroundColor: '#F1F1F1',
    height: 225,
    margin: 10,
    flexDirection: 'column',
  },
  space: {
    marginTop: 'auto',
  },
  old: {
    color: 'rgba(48, 48, 48, 0.2)',
    fontStyle: 'italic',
    textDecorationLine: 'line-through',
  },
  disc: {
    position: 'absolute',
    zIndex: 55,
    left: 0,
    width: 97,
    height: 23,
    backgroundColor: '#05944F',
    justifyContent: 'center',
    alignItems: 'center',
    top: 15,
    borderBottomEndRadius: 10,
    borderTopEndRadius: 10,
  },
  discText: {
    color: 'white',
    fontSize: 11,
  },
  price: {
    color: '#444',
    padding: 10,
    backgroundColor: '#ffffff',
    borderRadius: 10,
    elevation: 1,
    fontSize: 12,
    letterSpacing: 1,
  },
  foodName: {
    marginTop: 10,
    fontSize: 16,
  },
  line: {
    height: 3,
    width: 130,
    backgroundColor: ' rgba(196, 196, 196, 0.8)',
    margin: 10,
    borderRadius: 10,
    alignSelf: 'center',
  },
  list: {
    backgroundColor: 'white',
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    justifyContent: 'center',
    position: 'relative',
    width: '100%',
    height: '100%',
    bottom: 55,
    padding: 10,
    zIndex: 32,
    flex: 1,
  },

  calendar: {
    marginLeft: 20,
    borderColor: 'gray',
    borderWidth: 1,
    padding: 5,
    width: '35%',
    borderStyle: 'solid',
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginTop: 10,
  },
  date: {
    padding: 20,
  },
  scene: {
    flex: 1,
  },
  indicatorStyle: {
    backgroundColor: '#EEEEEE',
  },
  tabBar: {
    display: 'flex',
    justifyContent: 'center',
    alignContent: 'center',
    backgroundColor: '#EEEEEE',
    height: 33,
    width: '85%',
    alignSelf: 'center',
    marginBottom: 10,
    borderRadius: 50,
    elevation: 0,
    overflow: 'hidden',
    position: 'relative',
  },
  tabLabel: {
    color: 'rgba(48, 48, 48, 0.4)',
    bottom: 9,
    width: 70,
    // height: 30,
    textAlign: 'center',
    alignSelf: 'center',
    position: 'relative',
    alignContent: 'center',
    left: 0,
    // // alignItems: 'center',
    // fontSize: 10,
    // zIndex: 555,
  },
  focused: {
    display: 'flex',
    color: 'white',
    // top: 0,
    bottom: 15,
    fontSize: 12,
    backgroundColor: '#303030',
    borderRadius: 50,
    width: 110,
    height: 30,
    paddingTop: 7,
    left: -18,

    textAlign: 'center',
  },
});
